### ISSUE TITLE
Information about the site template

### ISSUE THREAD

**Issue by anuraghazra** [rishab-sharma/rishab-sharma.github.io#1]
Hi @rishab-sharma i got an email from formspree.com because you forgot to change my email to yours because of that formspree is asking for activation

You should edit this.
https://github.com/rishab-sharma/page/blob/2e9aa4a30143f1f423a92d2ea645a0851cf6110e/src/components/Contact/Contact.js#L29

-----

Also please don't change anything on the footer, i've spent countless hours developing the site and i would appreciate proper credits. 

https://github.com/rishab-sharma/page/blob/2e9aa4a30143f1f423a92d2ea645a0851cf6110e/src/components/Layout/Footer.js#L38

You could change the "by me" link text to "Anurag Hazra" linking to my [github account](https://github.com/anuraghazra) or the [original site](http://anuraghazra.github.io/). 

Thanks!

**Comment by rishab-sharma** [comment]
@anuraghazra Sure, I did a Find and Replace All - it must have replaced the footer. Sorry for that

**Comment by rishab-sharma** [comment]
@anuraghazra Just can you tell something about the GitHub actions you used. They seem to break-in mine in deploy stage.

**Comment by anuraghazra** [comment]
> @anuraghazra Just can you tell something about the GitHub actions you used. They seem to break-in mine in deploy stage.

I did not used Github action, it's deployed with Travis, and that github action workflow is not correct. don't use it

**Comment by rishab-sharma** [comment]
@anuraghazra I have updated the footer for https://rishab-sharma.github.io/page/  I hope it's ok. Also sorry for the emails you got. I just deployed it this morning. 
Thank you for the template.
